### PR TITLE
Bug fixes and quality of life features

### LINKED ISSUE #23: Hyperlink block's URL cuts off when editing
If the URL in the hyperlink block is too long it will be cut off when editing.

### PR DESCRIPTION
**Pull request by Chailotl**
Closes #23, #25, #26, #27, #28, #30, #31, #33

### CODE REVIEW

File: src/main/java/dev/hephaestus/glowcase/block/entity/ItemDisplayBlockEntity.java [hunk 1]
```diff
@@ -190,19 +191,29 @@ else return switch(this.givesItem) {
 		};
 	}
 	
-	public void giveTo(PlayerEntity player, Hand hand) {
-		player.setStackInHand(hand, getDisplayedStack().copy());
+	public void giveTo(PlayerEntity player) {
+		ItemStack itemStack = player.getStackInHand(Hand.MAIN_HAND);
+		boolean holdingSameAsDisplay = ItemStack.areItemsEqual(getDisplayedStack(), itemStack);
```
Comment (TheEpicBlock) [inline src/main/java/dev/hephaestus/glowcase/block/entity/ItemDisplayBlockEntity.java]: Subtle bug: this does not check for components. If you obtained some special unique renamed version of the item in the display it'll give you another one of the special item, even if the one in the display is just an unnamed item. Using `areItemsAndComponentsEqual` would be better here

File: src/main/java/dev/hephaestus/glowcase/client/gui/screen/ingame/HyperlinkBlockEditScreen.java [hunk 2]
```diff
@@ -24,10 +25,17 @@ public void init() {
 
 		if (this.client == null) return;
 
-		this.urlEntryWidget = new TextFieldWidget(this.client.textRenderer, width / 10, height / 2 - 10, 8 * width / 10, 20, Text.empty());
-		this.urlEntryWidget.setText(this.hyperlinkBlockEntity.getUrl());
+		this.titleEntryWidget = new TextFieldWidget(this.client.textRenderer, width / 10, height / 2 - 30, 8 * width / 10, 20, Text.empty());
+		this.titleEntryWidget.setMaxLength(Integer.MAX_VALUE);
```
Comment (TheEpicBlock) [inline src/main/java/dev/hephaestus/glowcase/client/gui/screen/ingame/HyperlinkBlockEditScreen.java]: Is this really best? I think people should have the freedom to go whatever length they'd like, but maybe we should put it at 1024 just to prevent people from accidentally pasting the entire bee movie script in there? /genq

File: src/main/java/dev/hephaestus/glowcase/client/gui/screen/ingame/HyperlinkBlockEditScreen.java [hunk 3]
```diff
@@ -24,10 +25,17 @@ public void init() {
...
+		this.titleEntryWidget.setText(this.hyperlinkBlockEntity.getTitle());
+		this.titleEntryWidget.setPlaceholder(Text.translatable("gui.glowcase.title"));
+
+		this.urlEntryWidget = new TextFieldWidget(this.client.textRenderer, width / 10, height / 2 + 10, 8 * width / 10, 20, Text.empty());
 		this.urlEntryWidget.setMaxLength(Integer.MAX_VALUE);
```
Comment (TheEpicBlock) [inline src/main/java/dev/hephaestus/glowcase/client/gui/screen/ingame/HyperlinkBlockEditScreen.java]: Same as above

File: src/main/java/dev/hephaestus/glowcase/client/gui/screen/ingame/HyperlinkBlockEditScreen.java (hunk 2 above)
Comment (TheEpicBlock) [reply src/main/java/dev/hephaestus/glowcase/client/gui/screen/ingame/HyperlinkBlockEditScreen.java]: (I'll note that this is just a passive comment, the pr doesn't even touch this value)

File: src/main/java/dev/hephaestus/glowcase/block/entity/ItemDisplayBlockEntity.java (hunk 1 above)
Comment (Chailotl) [reply src/main/java/dev/hephaestus/glowcase/block/entity/ItemDisplayBlockEntity.java]: Line 196 was copied verbatim from a different part of the code responsible for showing the item display block edit screen when holding the same item. Should that be fixed the same way?

File: src/main/java/dev/hephaestus/glowcase/client/gui/screen/ingame/HyperlinkBlockEditScreen.java (hunk 2 above)
Comment (Chailotl) [reply src/main/java/dev/hephaestus/glowcase/client/gui/screen/ingame/HyperlinkBlockEditScreen.java]: Although the text entry widget lets you paste arbitrarily large strings, the glowcase networking class already restricts it to 1024, but I think it would be a good idea to make this follow the same max length

File: src/main/java/dev/hephaestus/glowcase/block/entity/ItemDisplayBlockEntity.java (hunk 1 above)
Comment (TheEpicBlock) [reply src/main/java/dev/hephaestus/glowcase/block/entity/ItemDisplayBlockEntity.java]: Nah, I think it's useful to be able to edit the block even if you don't have the exact item, since they can get pretty complex

File: src/main/java/dev/hephaestus/glowcase/client/gui/screen/ingame/HyperlinkBlockEditScreen.java (hunk 2 above)
Comment (Chailotl) [reply src/main/java/dev/hephaestus/glowcase/client/gui/screen/ingame/HyperlinkBlockEditScreen.java]: Should I use `URL_MAX_LENGTH` inside `GlowcaseCommonNetworking` and make it public?

File: src/main/java/dev/hephaestus/glowcase/block/entity/ItemDisplayBlockEntity.java (hunk 1 above)
Comment (Chailotl) [reply src/main/java/dev/hephaestus/glowcase/block/entity/ItemDisplayBlockEntity.java]: Fixed with 92ba0a6783717c24135712743c1854d2d536aaf7

File: src/main/java/dev/hephaestus/glowcase/client/gui/screen/ingame/HyperlinkBlockEditScreen.java (hunk 2 above)
Comment (sleepingdragoninn) [reply src/main/java/dev/hephaestus/glowcase/client/gui/screen/ingame/HyperlinkBlockEditScreen.java]: go for it! or move it to HyperlinkBlockEntity and do the same

Comment (sleepingdragoninn) [reply src/main/java/dev/hephaestus/glowcase/client/gui/screen/ingame/HyperlinkBlockEditScreen.java]: done up in c6f928d because i'd like to clean out our PRs today

File: src/main/java/dev/hephaestus/glowcase/client/gui/screen/ingame/HyperlinkBlockEditScreen.java (hunk 3 above)
Comment (sleepingdragoninn) [reply src/main/java/dev/hephaestus/glowcase/client/gui/screen/ingame/HyperlinkBlockEditScreen.java]: done up in c6f928d because i'd like to clean out our PRs today
